# Setup
title: Wzom's blog
description: Temporarily only used for digital and electronic courses
url: https://github.com/238Uranium
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /background.png

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Wzom
  card: summary
logo: logo.png
social:
  name: Wzom
  links:
    - https://twitter.com/
    - https://github.com/238Uranium
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: 238Uranium
  url: https://github.com/238Uranium
  email: niuyugong@outlook.com

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git 
  repo: 
      github: git@github.com:238Uranium/238Uranium.github.io.git,gh-pages
      coding: git@git.coding.net:238Uranium/238Uranium.git,master
